# coding: utf-8

Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.network "private_network", ip: "192.168.42.10", virtualbox__intnet: "siknet", auto_config: true
    vm1.vm.provider "virtualbox" do |v|
      v.name = "vm1"
    end
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.network "private_network", ip: "192.168.42.11", virtualbox__intnet: "siknet", auto_config: true
    vm2.vm.provider "virtualbox" do |v|
      v.name = "vm2"
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.memory = 1024
    v.linked_clone = true
  end

  config.vm.box = "mimuw/sikvm"
end
