SET linesize 350
SET pagesize 60

CLEAR screen;

DROP table publikacje;

create table publikacje (
    ID NUMBER(6,0) PRIMARY KEY,
    Rok NUMBER(4,0),
    Autorzy NUMBER(2,0),
    Punkty NUMBER(3,0),
    Tytul VARCHAR2(195)
);

INSERT INTO publikacje VALUES (1, 2017, 2, 70, 'Function definitions for compound values in object-oriented languages');
INSERT INTO publikacje VALUES (2, 2017, 4, 140, 'Regular Separability of Parikh Automata');
INSERT INTO publikacje VALUES (3, 2017, 4, 140, 'Separability of Reachability Sets of Vector Addition Systems');
INSERT INTO publikacje VALUES (4, 2017, 4, 200, 'Timed pushdown automata and branching vector addition systems');
INSERT INTO publikacje VALUES (5, 2017, 2, 200, 'Regular separability of one counter automata');
INSERT INTO publikacje VALUES (6, 2017, 3, 20, 'Rule-Based Reasoning with Belief Structures');
INSERT INTO publikacje VALUES (7, 2017, 4, 20, 'Heterogeneous Approximate Reasoning with Graded Truth Values');
INSERT INTO publikacje VALUES (8, 2017, 1, 70, 'The Spectrum of Equilibria for the Colonel Blotto and the Colonel Lotto Games');
INSERT INTO publikacje VALUES (9, 2017, 3, 70, 'Detecting Locus Acquisition Events in Gene Trees');
INSERT INTO publikacje VALUES (10, 2017, 2, 70, 'New Algorithms for the Genomic Duplication Problem');
INSERT INTO publikacje VALUES (11, 2017, 5, 140, 'Bounding Average-Energy Games');
INSERT INTO publikacje VALUES (12, 2017, 4, 140, 'On Büchi One-Counter Automata');
INSERT INTO publikacje VALUES (13, 2017, 3, 200, 'Linear combinations of unordered data vectors');
INSERT INTO publikacje VALUES (14, 2017, 7, 20, 'SMIS 2017 Data Mining Competition: Trading Based on Recommendations');
INSERT INTO publikacje VALUES (15, 2017, 4, 200, 'Decremental Single-source Reachability in Planar Digraphs');
INSERT INTO publikacje VALUES (16, 2017, 6, 140, 'Contracting a Planar Graph Efficiently');
INSERT INTO publikacje VALUES (17, 2017, 2, 70, 'Modal mu-Calculus with Atoms');
INSERT INTO publikacje VALUES (18, 2017, 3, 140, 'Expressiveness of Probabilistic Modal Logics, Revisited');
INSERT INTO publikacje VALUES (19, 2017, 5, 200, 'Learning nominal automata');
INSERT INTO publikacje VALUES (20, 2017, 8, 140, 'Efficient Enumeration of Non-Equivalent Squares in Partial Words with Few Holes');
INSERT INTO publikacje VALUES (21, 2017, 2, 200, 'LOIS: Syntax and Semantics');
INSERT INTO publikacje VALUES (22, 2017, 3, 200, 'On the Computational Complexity of Gossip Protocols');
INSERT INTO publikacje VALUES (23, 2017, 2, 20, 'Programming Languages in GitHub: A Visualization in Hyperbolic Plane');
INSERT INTO publikacje VALUES (24, 2017, 3, 140, 'Improving TSP Tours Using Dynamic Programming over Tree Decompositions');
INSERT INTO publikacje VALUES (25, 2017, 4, 200, 'Approximation and Parameterized Complexity of Minimax Approval Voting');
INSERT INTO publikacje VALUES (26, 2017, 5, 140, 'Tight Lower Bounds for the Complexity of Multicoloring');
INSERT INTO publikacje VALUES (27, 2017, 2, 20, 'A Fast Deterministic Detection of Small Pattern Graphs in Graphs Without Large Cliques');
INSERT INTO publikacje VALUES (28, 2017, 3, 200, 'Axiomatic Characterization of Game-Theoretic Network Centralities');
INSERT INTO publikacje VALUES (29, 2017, 4, 200, 'The Dollar Auction with Spiteful Players');
INSERT INTO publikacje VALUES (30, 2017, 4, 200, 'On the Construction of Covert Networks');
INSERT INTO publikacje VALUES (31, 2017, 3, 200, 'Strategic Social Network Analysis');
INSERT INTO publikacje VALUES (32, 2017, 3, 140, 'Dynamic Beats Fixed: On Phase-Based Algorithms for File Migration');
INSERT INTO publikacje VALUES (33, 2017, 4, 140, 'On Problems Equivalent to (min, +)-Convolution');
INSERT INTO publikacje VALUES (34, 2017, 4, 70, 'Bisimilarity for paraconsistent description logics');
INSERT INTO publikacje VALUES (35, 2017, 4, 200, 'Why Do Cascade Sizes Follow a Power-Law?');
INSERT INTO publikacje VALUES (36, 2017, 2, 200, 'Approximation and Kernelization for Chordal Vertex Deletion');
INSERT INTO publikacje VALUES (37, 2017, 3, 70, 'Edge Bipartization Faster Than 2^k');
INSERT INTO publikacje VALUES (38, 2017, 2, 140, 'Subexponential Parameterized Algorithms for Graphs of Polynomial Growth');
INSERT INTO publikacje VALUES (39, 2017, 3, 140, 'Exploring the Complexity of Layout Parameters in Tournaments and Semi-Complete Digraphs');
INSERT INTO publikacje VALUES (40, 2017, 6, 200, 'Model-checking for successor-invariant first-order formulas on graph classes of bounded expansion');
INSERT INTO publikacje VALUES (41, 2017, 2, 140, 'Optimizing Tree Decompositions in MSO');
INSERT INTO publikacje VALUES (42, 2017, 5, 140, 'Linear Kernels for Edge Deletion Problems to Immersion-Closed Graph Classes');
INSERT INTO publikacje VALUES (43, 2017, 5, 200, 'Fully polynomial-time parameterized computations for graphs and matrices of low treewidth');
INSERT INTO publikacje VALUES (44, 2017, 5, 70, 'Cutwidth: Obstructions and Algorithmic Aspects');
INSERT INTO publikacje VALUES (45, 2017, 7, 140, 'Neighborhood Complexity and Kernelization for Nowhere Dense Classes of Graphs');
INSERT INTO publikacje VALUES (46, 2017, 3, 140, 'Approximation and Parameterized Algorithms for Geometric Independent Set with Shrinking');
INSERT INTO publikacje VALUES (47, 2017, 3, 140, 'On Low Rank-Width Colorings');
INSERT INTO publikacje VALUES (48, 2017, 2, 200, 'Streaming K-Mismatch with Error Correcting and Applications');
INSERT INTO publikacje VALUES (49, 2017, 5, 20, 'Palindromic Decompositions with Gaps and Errors');
INSERT INTO publikacje VALUES (50, 2017, 5, 70, 'Longest Common Factor After One Edit Operation');
INSERT INTO publikacje VALUES (51, 2017, 6, 70, 'Faster Algorithms for 1-Mappability of a Sequence');
INSERT INTO publikacje VALUES (52, 2017, 2, 140, 'Optimizing egalitarian performance in the side-effects model of colocation for data center resource management');
INSERT INTO publikacje VALUES (53, 2017, 4, 200, 'Negative-Weight Shortest Paths and Unit Capacity Minimum Cost Flow in Õ(m^10/7 log W) Time');
INSERT INTO publikacje VALUES (54, 2017, 2, 140, 'Improved Distance Queries and Cycle Counting by Frobenius Normal Form');
INSERT INTO publikacje VALUES (55, 2017, 2, 140, 'Approximate Nearest Neighbors Search Without False Negatives For l_2 For c>sqrtloglogn');
INSERT INTO publikacje VALUES (56, 2017, 2, 70, 'Automata Theory Approach to Predicate Intuitionistic Logic');
INSERT INTO publikacje VALUES (57, 2017, 2, 200, 'Attachment Centrality for Weighted Graphs');
INSERT INTO publikacje VALUES (58, 2017, 1, 70, 'Connecting Decidability and Complexity for MSO Logic');
INSERT INTO publikacje VALUES (59, 2017, 3, 140, 'A Characterisation of Pi^0_2 Regular Tree Languages');
INSERT INTO publikacje VALUES (60, 2017, 3, 20, 'Scalable Machine Learning with Granulated Data Summaries: A Case of Feature Selection');
INSERT INTO publikacje VALUES (61, 2017, 4, 140, 'When the Optimum is also Blind: a New Perspective on Universal Optimization');
INSERT INTO publikacje VALUES (62, 2018, 2, 140, 'Binary Reachability of Timed Pushdown Automata via Quantifier Elimination and Cyclic Order Atoms');
INSERT INTO publikacje VALUES (63, 2018, 4, 140, 'Online Facility Location with Deletions');
INSERT INTO publikacje VALUES (64, 2018, 6, 200, 'Universal Trees Grow Inside Separating Automata: Quasi-Polynomial Lower Bounds for Parity Games');
INSERT INTO publikacje VALUES (65, 2018, 3, 140, 'Unboundedness Problems for Languages of Vector Addition Systems');
INSERT INTO publikacje VALUES (66, 2018, 6, 140, 'Regular Separability of Well-Structured Transition Systems');
INSERT INTO publikacje VALUES (67, 2018, 3, 200, 'FairSwap: How To Fairly Exchange Digital Goods');
INSERT INTO publikacje VALUES (68, 2018, 3, 200, 'General State Channel Networks');
INSERT INTO publikacje VALUES (69, 2018, 3, 200, 'Individual Security and Network Design with Malicious Nodes');
INSERT INTO publikacje VALUES (70, 2018, 6, 70, 'The Wasserstein Distance as a Dissimilarity Measure for Mass Spectra with Application to Spectral Deconvolution');
INSERT INTO publikacje VALUES (71, 2018, 3, 140, 'Cophenetic Distances: A Near-Linear Time Algorithmic Framework');
INSERT INTO publikacje VALUES (72, 2018, 2, 140, 'Linear Equations with Ordered Data');
INSERT INTO publikacje VALUES (73, 2018, 2, 140, 'The IPv6 Routing Protocol for Low-power and Lossy Networks (RPL) under Network Partitions');
INSERT INTO publikacje VALUES (74, 2018, 3, 140, 'Ad Hoc 802.11-802.15.4 Crosstalk-Based Communication in Practice');
INSERT INTO publikacje VALUES (75, 2018, 2, 70, 'On Designing Provably Correct DODAG Formation Criteria for the IPv6 Routing Protocol for Low-Power and Lossy Networks (RPL)');
INSERT INTO publikacje VALUES (76, 2018, 1, 140, 'A Distributed Systems Perspective on Industrial IoT');
INSERT INTO publikacje VALUES (77, 2018, 2, 70, 'Investigating Similarity between Hearthstone Cards: Text Embeddings and Interchangeability Approaches');
INSERT INTO publikacje VALUES (78, 2018, 3, 20, 'Improving Hearthstone AI by Combining MCTS and Supervised Learning Algorithms');
INSERT INTO publikacje VALUES (79, 2018, 1, 200, 'Decremental Transitive Closure and Shortest Paths for Planar Digraphs and Beyond');
INSERT INTO publikacje VALUES (80, 2018, 5, 200, 'Optimal Dynamic Strings');
INSERT INTO publikacje VALUES (81, 2018, 2, 140, 'Improved Bounds for Shortest Paths in Dense Distance Graphs');
INSERT INTO publikacje VALUES (82, 2018, 5, 140, 'Decremental SPQR-trees for Planar Graphs');
INSERT INTO publikacje VALUES (83, 2018, 4, 20, 'On Periodicity Lemma for Partial Words');
INSERT INTO publikacje VALUES (84, 2018, 6, 70, 'Faster Recovery of Approximate Periods over Edit Distance');
INSERT INTO publikacje VALUES (85, 2018, 8, 70, 'Linear-Time Algorithm for Long LCF with k Mismatches');
INSERT INTO publikacje VALUES (86, 2018, 6, 140, 'String Periods in the Order-Preserving Model');
INSERT INTO publikacje VALUES (87, 2018, 7, 70, 'Efficient Computation of Sequence Mappability');
INSERT INTO publikacje VALUES (88, 2018, 6, 140, 'On Directed Feedback Vertex Set Parameterized by Treewidth');
INSERT INTO publikacje VALUES (89, 2018, 2, 140, 'WQO Dichotomy for 3-Graphs');
INSERT INTO publikacje VALUES (90, 2018, 6, 200, 'Quantifying Algorithmic Improvements over Time');
INSERT INTO publikacje VALUES (91, 2018, 3, 200, 'Finite Query Answering in Expressive Description Logics with Transitive Roles');
INSERT INTO publikacje VALUES (92, 2018, 6, 20, 'On Fuzzy Sheffer Stroke Operation');
INSERT INTO publikacje VALUES (93, 2018, 1, 140, 'Recursion Schemes and the WMSO+U Logic');
INSERT INTO publikacje VALUES (94, 2018, 1, 70, 'The Complexity of the Diagonal Problem for Recursion Schemes');
INSERT INTO publikacje VALUES (95, 2018, 2, 140, 'An Improved FPT Algorithm for Independent Feedback Vertex Set');
INSERT INTO publikacje VALUES (96, 2018, 3, 200, 'On Subexponential Parameterized Algorithms for Steiner Tree and Directed Subset TSP on Planar Graphs');
INSERT INTO publikacje VALUES (97, 2018, 2, 70, 'Experimental Evaluation of Parameterized Algorithms for Feedback Vertex Set');
INSERT INTO publikacje VALUES (98, 2018, 2, 70, 'Finding Hamiltonian Cycle in Graphs of Bounded Treewidth: Experimental Evaluation');
INSERT INTO publikacje VALUES (99, 2018, 5, 70, 'Empirical Evaluation of Approximation Algorithms for Generalized Graph Coloring and Uniform Quasi-Wideness');
INSERT INTO publikacje VALUES (100, 2018, 7, 140, 'First-Order Interpretations of Bounded Expansion Classes');
INSERT INTO publikacje VALUES (101, 2018, 3, 140, 'Quasi-Polynomial Time Approximation Schemes for Packing and Covering Problems in Planar Graphs');
INSERT INTO publikacje VALUES (102, 2018, 3, 200, 'Parameterized circuit complexity of model-checking on sparse structures');
INSERT INTO publikacje VALUES (103, 2018, 3, 200, 'Definable decompositions for graphs of bounded linear cliquewidth');
INSERT INTO publikacje VALUES (104, 2018, 3, 200, 'On the number of types in sparse graphs');
INSERT INTO publikacje VALUES (105, 2018, 4, 70, 'Broadcast with Energy-Exchanging Mobile Agents Distributed on a Tree');
INSERT INTO publikacje VALUES (106, 2018, 2, 20, 'Dfuntest: A Testing Framework for Distributed Applications');
INSERT INTO publikacje VALUES (107, 2018, 3, 200, 'Collective Schedules: Scheduling Meets Computational Social Choice');
INSERT INTO publikacje VALUES (108, 2018, 3, 70, 'Reducing Transducer Equivalence to Register Automata Problems Solved by "Hilbert Method');
INSERT INTO publikacje VALUES (109, 2018, 2, 200, 'Approval-Based Multi-Winner Rules and Strategic Voting');
INSERT INTO publikacje VALUES (110, 2018, 2, 200, 'Consistent Approval-Based Multi-Winner Rules');
INSERT INTO publikacje VALUES (111, 2018, 3, 200, 'Stable Marriage with Multi-Modal Preferences');
INSERT INTO publikacje VALUES (112, 2018, 5, 200, 'Multiwinner Elections With Diversity Constraints');
INSERT INTO publikacje VALUES (113, 2018, 6, 200, 'On the Complexity of Extended and Proportional Justified Representation');
INSERT INTO publikacje VALUES (114, 2018, 3, 140, 'Proportional Approval Voting, Harmonic k-median, and Negative Association');
INSERT INTO publikacje VALUES (115, 2018, 3, 70, 'How Deterministic are Good-For-Games Automata?');
INSERT INTO publikacje VALUES (116, 2018, 1, 140, 'Unambiguous Languages Exhaust the Index Hierarchy');
INSERT INTO publikacje VALUES (117, 2018, 2, 70, 'Investigating Similarity between Hearthstone Cards: Text Embeddings and Interchangeability Approaches');
INSERT INTO publikacje VALUES (118, 2018, 3, 70, 'Ranking mutual information dependencies in a summary-based approximate analytics framework');
INSERT INTO publikacje VALUES (119, 2018, 2, 200, 'On computability and tractability for infinite sets');
INSERT INTO publikacje VALUES (120, 2018, 2, 200, 'An Axiomatization of the Eigenvector and Katz Centralities');
INSERT INTO publikacje VALUES (121, 2018, 2, 200, 'Axiomatization of the PageRank Centrality');
INSERT INTO publikacje VALUES (122, 2018, 2, 200, 'Random Order Contention Resolution Schemes');
INSERT INTO publikacje VALUES (123, 2019, 7, 200, 'Multi3Net: Segmenting Flooded Buildings via Fusion of Multiresolution, Multisensor, and Multitemporal Satellite Imagery');
INSERT INTO publikacje VALUES (124, 2019, 3, 140, 'String-to-String Interpretations With Polynomial-Size Output');
INSERT INTO publikacje VALUES (125, 2019, 2, 70, 'A non-regular language of infinite trees that is recognizable by a sort-wise finite algebra');
INSERT INTO publikacje VALUES (126, 2019, 4, 70, 'Regular tree languages in low levels of the Wadge Hierarchy');
INSERT INTO publikacje VALUES (127, 2019, 3, 200, 'MSO+nabla is undecidable');
INSERT INTO publikacje VALUES (128, 2019, 2, 140, 'Occupational injury risk wage premium');
INSERT INTO publikacje VALUES (129, 2019, 3, 140, 'Timed Basic Parallel Processes');
INSERT INTO publikacje VALUES (130, 2019, 2, 70, 'Efficient reduction of nondeterministic automata with application to language inclusion testing');
INSERT INTO publikacje VALUES (131, 2019, 4, 100, 'Binary Reachability of Timed-register Pushdown Automata and Branching Vector Addition Systems');
INSERT INTO publikacje VALUES (132, 2019, 4, 140, 'On Problems Equivalent to (min, +)-Convolution');
INSERT INTO publikacje VALUES (133, 2019, 3, 140, 'Improving TSP Tours Using Dynamic Programming over Tree Decompositions');
INSERT INTO publikacje VALUES (134, 2019, 5, 200, 'Minimum Bisection Is Fixed-Parameter Tractable');
INSERT INTO publikacje VALUES (135, 2019, 6, 140, 'Applying deep learning to right whale photo identification');
INSERT INTO publikacje VALUES (136, 2019, 5, 70, 'Shortest paths in one-counter systems');
INSERT INTO publikacje VALUES (137, 2019, 2, 70, 'Regular Separability of One Counter Automata');
INSERT INTO publikacje VALUES (138, 2019, 5, 200, 'The Reachability Problem for Petri Nets is Not Elementary');
INSERT INTO publikacje VALUES (139, 2019, 4, 140, 'New Pumping Technique for 2-Dimensional VASS');
INSERT INTO publikacje VALUES (140, 2019, 3, 140, 'Improved Bounds for the Excluded-Minor Approximation of Treedepth');
INSERT INTO publikacje VALUES (141, 2019, 4, 100, 'Energy-optimal broadcast and exploration in a tree using mobile agents');
INSERT INTO publikacje VALUES (142, 2019, 12, 200, 'qDSB-Seq is a general method for genome-wide quantification of DNA double-strand breaks using sequencing');
INSERT INTO publikacje VALUES (143, 2019, 3, 40, 'A paraconsistent approach to actions in informationally complex environments');
INSERT INTO publikacje VALUES (144, 2019, 3, 70, 'Belief Shadowing');
INSERT INTO publikacje VALUES (145, 2019, 3, 70, 'Doxastic Group Reasoning via Multiple Belief Shadowing');
INSERT INTO publikacje VALUES (146, 2019, 2, 20, 'BDI Model of Connected and Autonomous Vehicles');
INSERT INTO publikacje VALUES (147, 2019, 3, 140, 'Simple Refreshing in the Noisy Leakage Model');
INSERT INTO publikacje VALUES (148, 2019, 3, 100, 'Unifying Leakage Models: From Probing Attacks to Noisy Leakage');
INSERT INTO publikacje VALUES (149, 2019, 4, 200, 'Perun: Virtual Payment Hubs over Cryptocurrencies');
INSERT INTO publikacje VALUES (150, 2019, 5, 200, 'Multi-party Virtual State Channels');
INSERT INTO publikacje VALUES (151, 2019, 4, 140, 'Progressive Algorithms for Domination and Independence');
INSERT INTO publikacje VALUES (152, 2019, 4, 100, 'Jaccard/Tanimoto similarity test and estimation methods for biological presence-absence data');
INSERT INTO publikacje VALUES (153, 2019, 9, 200, 'Automatic mapping of atoms across both simple and complex chemical reactions');
INSERT INTO publikacje VALUES (154, 2019, 5, 70, 'Biologically sound formal model of Hsp70 heat induction');
INSERT INTO publikacje VALUES (155, 2019, 10, 140, 'MIND: A double-linear model to accurately determine monoisotopic precursor mass in high-resolution top-down proteomics');
INSERT INTO publikacje VALUES (156, 2019, 4, 70, 'Truncated Robust Principal Component Analysis and Noise Reduction for Single Cell RNA Sequencing Data');
INSERT INTO publikacje VALUES (157, 2019, 7, 140, 'masstodon: A tool for assigning peaks and modeling electron transfer reactions in top-down mass spectrometry');
INSERT INTO publikacje VALUES (158, 2019, 22, 140, 'Mapping of breakpoints in balanced chromosomal translocations by shallow whole genome sequencing points to EFNA5, BAHD1 and PPP2R5E as novel candidates for genes causing human Mendelian disorders');
INSERT INTO publikacje VALUES (159, 2019, 2, 70, 'Credibility of Evolutionary Events in Gene Trees');
INSERT INTO publikacje VALUES (160, 2019, 4, 70, 'Mathematical properties of the gene duplication cost');
INSERT INTO publikacje VALUES (161, 2019, 3, 140, 'Feasibility Algorithms for the Duplication-Loss Cost');
INSERT INTO publikacje VALUES (162, 2019, 13, 200, 'High-Throughput BCR Sequencing and Single-Cell Transcriptomics Reveal Distinct Transcriptional Profiles Associated with Subclonal Evolution of Follicular Lymphoma');
INSERT INTO publikacje VALUES (163, 2019, 4, 140, 'Continuous Reachability for Unordered Data Petri Nets is in PTime');
INSERT INTO publikacje VALUES (164, 2019, 7, 140, '30 Sensors to Mars: Toward Distributed Support Systems for Astronauts in Space Habitats');
INSERT INTO publikacje VALUES (165, 2019, 5, 140, 'GRUNGE: A Grand Unified ATP Challenge');
INSERT INTO publikacje VALUES (166, 2019, 2, 140, 'Declarative Proof Translation');
INSERT INTO publikacje VALUES (167, 2019, 3, 140, 'Higher-Order Tarski Grothendieck as a Foundation for Formal Proof');
INSERT INTO publikacje VALUES (168, 2019, 2, 140, 'Reliable Hubs for Partially-Dynamic All-Pairs Shortest Paths in Directed Graphs');
INSERT INTO publikacje VALUES (169, 2019, 2, 140, 'Min-Cost Flow in Unit-Capacity Planar Graphs');
INSERT INTO publikacje VALUES (170, 2019, 5, 200, 'Codensity Games for Bisimilarity');
INSERT INTO publikacje VALUES (171, 2019, 2, 70, 'Scalar and Vectorial mu-calculus with Atoms');
INSERT INTO publikacje VALUES (172, 2019, 2, 200, 'History-Dependent Nominal mu-Calculus');
INSERT INTO publikacje VALUES (173, 2019, 4, 70, 'Expressiveness of probabilistic modal logics: A gradual approach');
INSERT INTO publikacje VALUES (174, 2019, 5, 70, 'Definable isomorphism problem');
INSERT INTO publikacje VALUES (175, 2019, 2, 70, 'Logical properties of random graphs from small addable classes');
INSERT INTO publikacje VALUES (176, 2019, 4, 140, 'Fine-Grained Complexity of k-OPT in Bounded-Degree Graphs for Solving TSP');
INSERT INTO publikacje VALUES (177, 2019, 5, 70, 'Tight Lower Bounds for the Complexity of Multicoloring');
INSERT INTO publikacje VALUES (178, 2019, 2, 140, 'Rare Siblings Speed-Up Deterministic Detection and Counting of Small Pattern Graphs');
INSERT INTO publikacje VALUES (179, 2019, 2, 100, 'A fast deterministic detection of small pattern graphs in graphs without large cliques');
INSERT INTO publikacje VALUES (180, 2019, 7, 140, 'Structure and function of the Ts2631 endolysin of Thermus scotoductus phage vB_Tsc2631 with unique N-terminal extension used for peptidoglycan binding');
INSERT INTO publikacje VALUES (181, 2019, 4, 140, 'Enumerating Connected Subgraphs and Computing the Myerson and Shapley Values in Graph-restricted Games');
INSERT INTO publikacje VALUES (182, 2019, 4, 200, 'Attachment Centrality: Measure for Connectivity in Networks');
INSERT INTO publikacje VALUES (183, 2019, 3, 140, 'Strategic Attack '||'&'||' Defense in Security Diffusion Games');
INSERT INTO publikacje VALUES (184, 2019, 5, 200, 'Attacking Similarity-Based Link Prediction in Social Networks');
INSERT INTO publikacje VALUES (185, 2019, 5, 100, 'A Measure of Added Value in Groups');
INSERT INTO publikacje VALUES (186, 2019, 6, 140, 'How to Hide one’s Relationships from Link prediction Algorithms');
INSERT INTO publikacje VALUES (187, 2019, 3, 200, 'Adversarial Robustness of Similarity-Based Link Prediction');
INSERT INTO publikacje VALUES (188, 2019, 3, 200, 'A Subquadratic Approximation Scheme for Partition');
INSERT INTO publikacje VALUES (189, 2019, 4, 140, 'Equal-subset-sum faster than the meet-in-the-middle');
INSERT INTO publikacje VALUES (190, 2019, 3, 70, 'On the semantics of Cypher''s implicit group-by');
INSERT INTO publikacje VALUES (191, 2019, 5, 200, 'On Finite and Unrestricted Query Entailment beyond SQ with Number Restrictions on Transitive Roles');
INSERT INTO publikacje VALUES (192, 2019, 2, 70, 'Credibility of Evolutionary Events in Gene Trees');
INSERT INTO publikacje VALUES (193, 2019, 1, 100, 'The Influence of the Test Operator on the Expressive Power of PDL-like Logics');
INSERT INTO publikacje VALUES (194, 2019, 1, 200, 'Bisimilarity in Fuzzy Description Logics Under the Zadeh Semantics');
INSERT INTO publikacje VALUES (195, 2019, 2, 70, 'Minimizing interpretations in fuzzy description logics under the Gödel semantics by using fuzzy bisimulations');
INSERT INTO publikacje VALUES (196, 2019, 2, 100, 'An expressive and tractable rule-based description language');
INSERT INTO publikacje VALUES (197, 2019, 2, 20, 'Bisimulations for Fuzzy Description Logics with Involutive Negation Under the Gödel Semantics');
INSERT INTO publikacje VALUES (198, 2019, 2, 20, 'Incorporating Stratified Negation into Query-Subquery Nets for Evaluating Queries to Stratified Deductive Databases');
INSERT INTO publikacje VALUES (199, 2019, 5, 200, 'PyLink: a PyMOL plugin to identify links');
INSERT INTO publikacje VALUES (200, 2019, 3, 140, 'Defining and detecting links in chromosomes');
INSERT INTO publikacje VALUES (201, 2019, 1, 140, 'Parity Games: Zielonka''s Algorithm in Quasi-Polynomial Time');
INSERT INTO publikacje VALUES (202, 2019, 1, 20, 'Extensions of the Caucal Hierarchy?');
INSERT INTO publikacje VALUES (203, 2019, 2, 140, 'Inferring duplication episodes from unrooted gene trees');
INSERT INTO publikacje VALUES (204, 2019, 2, 70, 'Efficient algorithms for genomic duplication models');
INSERT INTO publikacje VALUES (205, 2019, 1, 100, 'The Worst Balanced Partially Ordered Sets—Ladders with Broken Rungs');
INSERT INTO publikacje VALUES (206, 2019, 2, 100, 'Finding Hamiltonian Cycle in Graphs of Bounded Treewidth: Experimental Evaluation');
INSERT INTO publikacje VALUES (207, 2019, 2, 70, 'Deleting Vertices to Graphs of Bounded Genus');
INSERT INTO publikacje VALUES (208, 2019, 3, 70, 'An Exponential Lower Bound for Cut Sparsifiers in Planar Graphs');
INSERT INTO publikacje VALUES (209, 2019, 4, 200, 'Polynomial-time algorithm for Maximum Weight Independent Set on P6-free graphs');
INSERT INTO publikacje VALUES (210, 2019, 3, 70, 'Turing Kernelization for Finding Long Paths in Graph Classes Excluding a Topological Minor');
INSERT INTO publikacje VALUES (211, 2019, 5, 100, 'Empirical Evaluation of Approximation Algorithms for Generalized Graph Coloring and Uniform Quasi-wideness');
INSERT INTO publikacje VALUES (212, 2019, 6, 70, 'Subexponential-Time Algorithms for Maximum Independent Set in P_t-Free and Broom-Free Graphs');
INSERT INTO publikacje VALUES (213, 2019, 3, 140, 'A Deterministic Polynomial Kernel for Odd Cycle Transversal and Vertex Multiway Cut in Planar Graphs');
INSERT INTO publikacje VALUES (214, 2019, 3, 140, 'Efficient Approximation Schemes for Uniform-Cost Clustering Problems in Planar Graphs');
INSERT INTO publikacje VALUES (215, 2019, 5, 140, 'Packing Directed Circuits Quarter-Integrally');
INSERT INTO publikacje VALUES (216, 2019, 3, 200, 'A Polynomial-Time Approximation Scheme for Facility Location on Planar Graphs');
INSERT INTO publikacje VALUES (217, 2019, 2, 200, 'Polynomial bounds for centered colorings on proper minor-closed graph classes');
INSERT INTO publikacje VALUES (218, 2019, 6, 70, 'Subexponential-Time Algorithms for Finding Large Induced Sparse Subgraphs');
INSERT INTO publikacje VALUES (219, 2019, 6, 140, 'Integer Programming and Incidence Treedepth');
INSERT INTO publikacje VALUES (220, 2019, 2, 140, 'Reachability for Bounded Branching VASS');
INSERT INTO publikacje VALUES (221, 2019, 2, 140, 'On width measures and topological problems on semi-complete digraphs');
INSERT INTO publikacje VALUES (222, 2019, 4, 140, 'On Geometric Set Cover for Orthants');
INSERT INTO publikacje VALUES (223, 2019, 3, 140, 'Tight Complexity Lower Bounds for Integer Linear Programming with Few Constraints');
INSERT INTO publikacje VALUES (224, 2019, 2, 100, 'A note on the complexity of a phaseless polynomial interpolation');
INSERT INTO publikacje VALUES (225, 2019, 6, 20, 'Efficient Representation and Counting of Antipower Factors in Words');
INSERT INTO publikacje VALUES (226, 2019, 9, 70, 'Quasi-Linear-Time Algorithm for Longest Common Circular Factor');
INSERT INTO publikacje VALUES (227, 2019, 8, 140, 'Circular Pattern Matching with k Mismatches');
INSERT INTO publikacje VALUES (228, 2019, 8, 70, 'Weighted Shortest Common Supersequence Problem Revisited');
INSERT INTO publikacje VALUES (229, 2019, 4, 70, 'On-line weighted pattern matching');
INSERT INTO publikacje VALUES (230, 2019, 3, 70, 'Longest Common Substring with Approximately k Mismatches');
INSERT INTO publikacje VALUES (231, 2019, 3, 70, 'Quasi-Periodicity in Streams');
INSERT INTO publikacje VALUES (232, 2019, 3, 40, 'Pattern Matching and Consensus Problems on Weighted Sequences and Profiles');
INSERT INTO publikacje VALUES (233, 2019, 4, 140, 'Longest Common Substring Made Fully Dynamic');
INSERT INTO publikacje VALUES (234, 2019, 6, 140, 'Internal Dictionary Matching');
INSERT INTO publikacje VALUES (235, 2019, 2, 20, 'Syntactic View of Sigma-Tau Generation of Permutations');
INSERT INTO publikacje VALUES (236, 2019, 2, 140, 'Optimizing Egalitarian Performance when Colocating Tasks with Types for Cloud Data Center Resource Management');
INSERT INTO publikacje VALUES (237, 2019, 5, 200, '(1 + epsilon)-Approximate Incremental Matching in Constant Deterministic Amortized Time');
INSERT INTO publikacje VALUES (238, 2019, 2, 200, 'Fair Knapsack');
INSERT INTO publikacje VALUES (239, 2019, 2, 200, 'A Quantitative Analysis of Multi-Winner Rules');
INSERT INTO publikacje VALUES (240, 2019, 2, 200, 'Approval-Based Elections and Distortion of Voting Rules');
INSERT INTO publikacje VALUES (241, 2019, 4, 70, 'Committee Scoring Rules: Axiomatic Characterization and Hierarchy');
INSERT INTO publikacje VALUES (242, 2019, 3, 200, 'Axiomatic characterization of committee scoring rules');
INSERT INTO publikacje VALUES (243, 2019, 4, 200, 'Proportional Representation in Elections: STV vs PAV');
INSERT INTO publikacje VALUES (244, 2019, 3, 200, 'Matchings under Preferences: Strength of Stability and Trade-Offs');
INSERT INTO publikacje VALUES (245, 2019, 5, 200, 'How Similar Are Two Elections?');
INSERT INTO publikacje VALUES (246, 2019, 3, 140, 'Uniformisation Gives the Full Strength of Regular Languages');
INSERT INTO publikacje VALUES (247, 2019, 4, 70, 'The logical strength of Büchi''s decidability theorem');
INSERT INTO publikacje VALUES (248, 2019, 10, 20, 'Multivariate Ovulation Window Detection at OvuFriend');
INSERT INTO publikacje VALUES (249, 2019, 2, 70, 'On Boolean Representation of Continuous Data Biclustering');
INSERT INTO publikacje VALUES (250, 2019, 2, 200, 'On resilient feature selection: Computational foundations of r-C-reducts');
INSERT INTO publikacje VALUES (251, 2019, 3, 40, 'Paraconsistent Reasoning in Cops and Robber Game with Uncertain Information: A Simulation-Based Analysis');
INSERT INTO publikacje VALUES (252, 2019, 1, 20, 'Decision-Making Support Using Nonmonotonic Probabilistic Reasoning');
INSERT INTO publikacje VALUES (253, 2019, 2, 200, 'Learning signaling networks from combinatorial perturbations by exploiting siRNA off-target effects');
INSERT INTO publikacje VALUES (254, 2019, 4, 140, 'ARA: accurate, reliable and active histopathological image classification framework with Bayesian deep learning');
INSERT INTO publikacje VALUES (255, 2019, 3, 100, 'QChromosomeVisualizer: A new tool for 3D visualization of long simulations of polymer-like chromosome models');
INSERT INTO publikacje VALUES (256, 2019, 3, 200, 'Random Walk Decay Centrality');
INSERT INTO publikacje VALUES (257, 2019, 3, 200, 'Approximating APSP without Scaling: Equivalence of Approximate Min-plus and Exact Min-Max');
INSERT INTO publikacje VALUES (258, 2019, 2, 70, 'BPscore: an effective metric for meaningful comparisons of structural chromosome segmentations');
INSERT INTO publikacje VALUES (259, 2019, 1, 70, 'Clifford Algebras Meet Tree Decompositions');
INSERT INTO publikacje VALUES (260, 2019, 5, 200, 'Losing Treewidth by Separating Subsets');
INSERT INTO publikacje VALUES (261, 2019, 5, 140, 'Constant-Factor FPT Approximation for Capacitated k-Median');
INSERT INTO publikacje VALUES (262, 2020, 15, 140, 'Lessons from Communication Problems that Nearly Jeopardized Development of Hardware-Software Support for a 1000-Device IoT Testbed');
INSERT INTO publikacje VALUES (263, 2020, 4, 140, 'ImaGINator: Conditional Spatio-Temporal GAN for Video Generation');
INSERT INTO publikacje VALUES (264, 2020, 4, 200, 'G3AN: Disentangling motion and appearance for video generation');
INSERT INTO publikacje VALUES (265, 2020, 4, 200, 'Extensions of ω-Regular Languages');
INSERT INTO publikacje VALUES (266, 2020, 2, 200, 'First-order tree-to-tree functions');
INSERT INTO publikacje VALUES (267, 2020, 2, 140, 'Single-Use Automata and Transducers for Infinite Alphabets');
INSERT INTO publikacje VALUES (268, 2020, 2, 140, 'Some Remarks on Deciding Equivalence for Graph-To-Graph Transducers');
INSERT INTO publikacje VALUES (269, 2020, 5, 70, 'Undecidability of a weak version of MSO+U');
INSERT INTO publikacje VALUES (270, 2020, 7, 200, 'From Gap-Exponential Time Hypothesis to Fixed Parameter Tractable Inapproximability: Clique, Dominating Set, and More');
INSERT INTO publikacje VALUES (271, 2020, 5, 140, 'Lower Bounds for the Parameterized Complexity of Minimum Fill-in and Other Completion Problems');
INSERT INTO publikacje VALUES (272, 2020, 2, 200, 'An Approach to Regular Separability in Vector Addition Systems');
INSERT INTO publikacje VALUES (273, 2020, 5, 140, 'Reachability in Fixed Dimension Vector Addition Systems with States');
INSERT INTO publikacje VALUES (274, 2020, 3, 140, 'Universality Problem for Unambiguous VASS');
INSERT INTO publikacje VALUES (275, 2020, 2, 140, 'Getting insight into the pan-genome structure with PangTree');
INSERT INTO publikacje VALUES (276, 2020, 4, 140, 'Dimensionality Reduction for k-Distance Applied to Persistent Homology');
INSERT INTO publikacje VALUES (277, 2020, 3, 200, 'A game of hide and seek in networks');
INSERT INTO publikacje VALUES (278, 2020, 3, 200, 'The strategy of conquest');
INSERT INTO publikacje VALUES (279, 2020, 4, 140, 'A PTAS for Euclidean TSP with Hyperplane Neighborhoods');
INSERT INTO publikacje VALUES (280, 2020, 6, 20, 'Drawing graphs on few lines and few planes');
INSERT INTO publikacje VALUES (281, 2020, 3, 100, 'Low Entropy Sub-Networks Prevent the Integration of Metabolomic and Transcriptomic Data');
INSERT INTO publikacje VALUES (282, 2020, 7, 70, 'Masserstein: Linear regression of mass spectra by optimal transport');
INSERT INTO publikacje VALUES (283, 2020, 3, 200, 'Knot_pull—python package for biopolymer smoothing and knot detection');
INSERT INTO publikacje VALUES (284, 2020, 20, 140, 'Breakpoint mapping of symptomatic balanced translocations links the EPHA6, KLF13 and UBR3 genes to novel disease phenotype');
INSERT INTO publikacje VALUES (285, 2020, 9, 140, 'New Hybrid Quantum Annealing Algorithms for Solving Vehicle Routing Problem');
INSERT INTO publikacje VALUES (286, 2020, 3, 100, 'Exact median-tree inference for unrooted reconciliation costs');
INSERT INTO publikacje VALUES (287, 2020, 3, 70, 'Minimizing genomic duplication episodes');
INSERT INTO publikacje VALUES (288, 2020, 4, 140, 'Parametrized Universality Problems for One-Counter Nets');
INSERT INTO publikacje VALUES (289, 2020, 5, 140, 'Human Nature: The Subject and the Headache of IoT-Based Sociometric Studies');
INSERT INTO publikacje VALUES (290, 2020, 4, 20, 'On Positive-Correlation-Promoting Reducts');
INSERT INTO publikacje VALUES (291, 2020, 2, 140, 'Single-Source Shortest Paths and Strong Connectivity in Dynamic Planar Graphs');
INSERT INTO publikacje VALUES (292, 2020, 1, 140, 'Bisimulational categoricity');
INSERT INTO publikacje VALUES (293, 2020, 5, 140, 'Many Visits TSP Revisited');
INSERT INTO publikacje VALUES (294, 2020, 2, 70, 'The Asymmetric Travelling Salesman Problem In Sparse Digraphs');
INSERT INTO publikacje VALUES (295, 2020, 6, 70, 'The PACE 2020 Parameterized Algorithms and Computational Experiments Challenge: Treedepth');
INSERT INTO publikacje VALUES (296, 2020, 2, 70, 'A simple approach to nondecreasing paths');
INSERT INTO publikacje VALUES (297, 2020, 9, 200, 'A High-Throughput Screen for Transcription Activation Domains Reveals Their Sequence Features and Permits Prediction by Deep Learning');
INSERT INTO publikacje VALUES (298, 2020, 2, 70, 'WQO dichotomy for 3-graph');
INSERT INTO publikacje VALUES (299, 2020, 5, 100, 'Petri net–based model of the human DNA base excision repair pathway');
INSERT INTO publikacje VALUES (300, 2020, 2, 70, 'Fair division in the presence of externalities');
INSERT INTO publikacje VALUES (301, 2020, 5, 200, 'Deep Learning Versus Traditional Solutions for Group Trajectory Outliers');
INSERT INTO publikacje VALUES (302, 2020, 3, 200, 'Hiding in Multilayer Networks');
INSERT INTO publikacje VALUES (303, 2020, 5, 70, 'Partition decision trees: representation for efficient computation of the Shapley value extended to games with externalities');
INSERT INTO publikacje VALUES (304, 2020, 5, 200, 'Signed Graph Games: Coalitional Games with Friends, Enemies and Allies');
INSERT INTO publikacje VALUES (305, 2020, 4, 200, 'The Manipulability of Centrality Measures-An Axiomatic Approach');
INSERT INTO publikacje VALUES (306, 2020, 2, 70, 'Improved approximation for Fractionally Subadditive Network Design');
INSERT INTO publikacje VALUES (307, 2020, 5, 200, 'On Finite Entailment of Non-Local Queries in Description Logics');
INSERT INTO publikacje VALUES (308, 2020, 6, 140, 'Ontology Focusing: Knowledge-Enriched Databases on Demand');
INSERT INTO publikacje VALUES (309, 2020, 5, 140, 'Bisimulation and bisimilarity for fuzzy description logics under the Gödel semantics');
INSERT INTO publikacje VALUES (310, 2020, 1, 140, 'ExpTime Tableaux with Global Caching for Hybrid PDL');
INSERT INTO publikacje VALUES (311, 2020, 3, 140, 'GLN: a method to reveal unique properties of lasso type topology in proteins');
INSERT INTO publikacje VALUES (312, 2020, 5, 140, 'Topoly: Python package to analyze topology of polymers');
INSERT INTO publikacje VALUES (313, 2020, 3, 140, 'Computing Measures of Weak-MSO Definable Sets of Trees');
INSERT INTO publikacje VALUES (314, 2020, 3, 70, 'A Quasi-Polynomial Black-Box Algorithm for Fixed Point Evaluation');
INSERT INTO publikacje VALUES (315, 2020, 1, 70, 'A Type System Describing Unboundedness');
INSERT INTO publikacje VALUES (316, 2020, 2, 200, 'Bisimulation Finiteness of Pushdown Systems Is Elementary');
INSERT INTO publikacje VALUES (317, 2020, 4, 140, 'Cost Automata, Safe Schemes, and Downward Closures');
INSERT INTO publikacje VALUES (318, 2020, 1, 70, 'Higher-Order Nonemptiness Step by Step');
INSERT INTO publikacje VALUES (319, 2020, 1, 70, 'On the Expressive Power of Higher-Order Pushdown Systems');
INSERT INTO publikacje VALUES (320, 2020, 1, 70, 'Parity Games: Another View on Lehtinen''s Algorithm');
INSERT INTO publikacje VALUES (321, 2020, 1, 70, 'Recursion Schemes, the MSO Logic, and the U quantifier');
INSERT INTO publikacje VALUES (322, 2020, 2, 70, 'A Double Exponential Lower Bound for the Distinct Vectors Problem');
INSERT INTO publikacje VALUES (323, 2020, 5, 140, 'The Complexity of Connectivity Problems in Forbidden-Transition Graphs And Edge-Colored Graphs');
INSERT INTO publikacje VALUES (324, 2020, 2, 40, 'An Improved FPT Algorithm for Independent Feedback Vertex Set');
INSERT INTO publikacje VALUES (325, 2020, 4, 100, 'On the Maximum Weight Independent Set Problem in Graphs without Induced Cycles of Length at Least Five');
INSERT INTO publikacje VALUES (326, 2020, 4, 200, 'Quasi-polynomial time approximation schemes for the Maximum Weight Independent Set Problem in H-free graphs');
INSERT INTO publikacje VALUES (327, 2020, 5, 70, 'Two lower bounds for p-centered colorings');
INSERT INTO publikacje VALUES (328, 2020, 4, 140, 'Hamiltonian Cycle Parameterized by Treedepth in Single Exponential Time and Polynomial Space');
INSERT INTO publikacje VALUES (329, 2020, 3, 200, 'Shorter Labeling Schemes for Planar Graphs');
INSERT INTO publikacje VALUES (330, 2020, 2, 140, 'VC Density of Set Systems Definable in Tree-Like Graphs');
INSERT INTO publikacje VALUES (331, 2020, 5, 200, 'An exponential time parameterized algorithm for planar disjoint paths');
INSERT INTO publikacje VALUES (332, 2020, 4, 100, 'Clustering Powers of Sparse Graphs');
INSERT INTO publikacje VALUES (333, 2020, 5, 140, 'Enumerating Minimal Dominating Sets in Kt-free Graphs and Variants');
INSERT INTO publikacje VALUES (334, 2020, 5, 140, 'Finding Large H-Colorable Subgraphs in Hereditary Graph Classes');
INSERT INTO publikacje VALUES (335, 2020, 7, 100, 'First-Order Interpretations of Bounded Expansion Classes');
INSERT INTO publikacje VALUES (336, 2020, 9, 100, 'Model-Checking on Ordered Structures');
INSERT INTO publikacje VALUES (337, 2020, 5, 140, 'On Polynomial Recursive Sequences');
INSERT INTO publikacje VALUES (338, 2020, 3, 100, 'On low rank-width colorings');
INSERT INTO publikacje VALUES (339, 2020, 3, 70, 'Quasi-Polynomial Time Approximation Schemes for Packing and Covering Problems in Planar Graphs');
INSERT INTO publikacje VALUES (340, 2020, 3, 70, 'Tight Complexity Lower Bounds for Integer Linear Programming with Few Constraints');
INSERT INTO publikacje VALUES (341, 2020, 5, 140, 'A Linear-Time Algorithm for Seeds Computation');
INSERT INTO publikacje VALUES (342, 2020, 4, 70, 'Approximating Longest Common Substring with k mismatches: Theory and Practice');
INSERT INTO publikacje VALUES (343, 2020, 8, 70, 'Counting Distinct Patterns in Internal Dictionary Matching');
INSERT INTO publikacje VALUES (344, 2020, 4, 70, 'Dynamic and Internal Longest Common Substring');
INSERT INTO publikacje VALUES (345, 2020, 2, 140, 'Efficient Computation of 2-Covers of a String');
INSERT INTO publikacje VALUES (346, 2020, 5, 70, 'Efficient Enumeration of Distinct Factors Using Package Representations');
INSERT INTO publikacje VALUES (347, 2020, 6, 100, 'Faster algorithms for 1-mappability of a sequence');
INSERT INTO publikacje VALUES (348, 2020, 5, 70, 'Indexing weighted sequences: Neat and efficient');
INSERT INTO publikacje VALUES (349, 2020, 7, 70, 'Internal Quasiperiod Queries');
INSERT INTO publikacje VALUES (350, 2020, 7, 20, 'Shortest Covers of All Cyclic Shifts of a String');
INSERT INTO publikacje VALUES (351, 2020, 2, 70, 'Streaming k-mismatch with error correcting and applications');
INSERT INTO publikacje VALUES (352, 2020, 6, 70, 'String periods in the order-preserving model');
INSERT INTO publikacje VALUES (353, 2020, 6, 140, 'The Number of Repetitions in 2D-Strings');
INSERT INTO publikacje VALUES (354, 2020, 5, 70, 'Unary Words Have the Smallest Levenshtein k-Neighbourhoods');
INSERT INTO publikacje VALUES (355, 2020, 5, 100, 'Universal reconstruction of a string');
INSERT INTO publikacje VALUES (356, 2020, 2, 70, 'k-Approximate Quasiperiodicity under Hamming and Edit Distance');
INSERT INTO publikacje VALUES (357, 2020, 11, 140, 'Autopilot: workload autoscaling at Google');
INSERT INTO publikacje VALUES (358, 2020, 2, 70, 'Scheduling Methods to Reduce Response Latency of Function as a Service');
INSERT INTO publikacje VALUES (359, 2020, 2, 100, 'Derived Hall algebras of one-cycle gentle algebras: The infinite global dimension case');
INSERT INTO publikacje VALUES (360, 2020, 1, 200, 'Complexity of Computing the Shapley Value in Games with Externalities');
INSERT INTO publikacje VALUES (361, 2020, 2, 200, 'Comparing election methods where each voter ranks only few candidates');
INSERT INTO publikacje VALUES (362, 2020, 3, 70, 'A characterization of the single-peaked single-crossing domain');
INSERT INTO publikacje VALUES (363, 2020, 5, 200, 'Drawing a map of elections in the space of statistical cultures');
INSERT INTO publikacje VALUES (364, 2020, 2, 200, 'Evaluating committees for representative democracies: The distortion and beyond');
INSERT INTO publikacje VALUES (365, 2020, 5, 100, 'Mixed integer programming with convex/concave constraints: Fixed-parameter tractability and applications to multicovering and voting');
INSERT INTO publikacje VALUES (366, 2020, 3, 200, 'Price of fairness in budget division and probabilistic social choice');
INSERT INTO publikacje VALUES (367, 2020, 2, 200, 'Proportionality and the Limits of Welfarism');
INSERT INTO publikacje VALUES (368, 2020, 2, 200, 'Utilitarian welfare and representation guarantees of approval-based multiwinner rules');
INSERT INTO publikacje VALUES (369, 2020, 4, 70, 'On the Succinctness of Alternating Parity Good-For-Games Automata');
INSERT INTO publikacje VALUES (370, 2020, 2, 140, 'Regular Choice Functions and Uniformisations For countable Domains');
INSERT INTO publikacje VALUES (371, 2020, 3, 200, 'Uniformisations of Regular Relations Over Bi-Infinite Words');
INSERT INTO publikacje VALUES (372, 2020, 4, 40, 'Research on Heuristic Optimization and Operations in IoT');
INSERT INTO publikacje VALUES (373, 2020, 2, 20, 'Approximate Decision Tree Induction over Approximately Engineered Data Features');
INSERT INTO publikacje VALUES (374, 2020, 4, 200, 'From Big Data to business analytics: The case study of churn prediction');
INSERT INTO publikacje VALUES (375, 2020, 3, 100, 'Heuristic Search of Exact Biclusters in Binary Data');
INSERT INTO publikacje VALUES (376, 2020, 4, 140, 'Rough-set-driven approach for attribute reduction in fuzzy formal concept analysis');
INSERT INTO publikacje VALUES (377, 2020, 2, 20, 'The Problem of Finding the Simplest Classifier Ensemble is NP-Hard – A Rough-Set-Inspired Formulation Based on Decision Bireducts');
INSERT INTO publikacje VALUES (378, 2020, 3, 140, 'IsoSpec2: Ultrafast Fine Structure Calculator');
INSERT INTO publikacje VALUES (379, 2020, 7, 200, 'Algorithmic Discovery of Tactical Combinations for Advanced Organic Syntheses');
INSERT INTO publikacje VALUES (380, 2020, 1, 20, 'A Paraconsistent ASP-like Language with Tractable Model Generation');
INSERT INTO publikacje VALUES (381, 2020, 1, 40, 'On the Probability and Cost of Ignorance, Inconsistency, Nonsense and More');
INSERT INTO publikacje VALUES (382, 2020, 2, 20, 'Rough Forgetting');
INSERT INTO publikacje VALUES (383, 2020, 4, 140, 'A mathematical model of the metastatic bottleneck predicts patient outcome and response to cancer treatment');
INSERT INTO publikacje VALUES (384, 2020, 52, 200, 'Eleven grand challenges in single-cell data science');
INSERT INTO publikacje VALUES (385, 2020, 8, 140, 'Feature selection strategies for drug sensitivity prediction');
INSERT INTO publikacje VALUES (386, 2020, 3, 70, 'The Unconstrained Diameters of the Duplication-Loss Cost and the Loss Cost');
INSERT INTO publikacje VALUES (387, 2020, 1, 200, 'Aggregate Queries on Sparse Databases');
INSERT INTO publikacje VALUES (388, 2020, 2, 200, 'Register Automata with Extrema Constraints, and an Application to Two-Variable Logic');
INSERT INTO publikacje VALUES (389, 2020, 2, 70, 'Automated inference of gene regulatory networks using explicit regulatory modules');




select * from publikacje where ROK = 2020 and PUNKTY/Autorzy >= 100 order by AUTORZY; 